services:
  app:
    build: .
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      APP_HOST: localhost:8080
    depends_on:
      - db
  db:
    image: docker.io/postgres:alpine3.18
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - todolist-db:/var/lib/postgresql/data
    expose:
      - 5432
      # healthcheck:
      #   test: ["CMD", "pg_isready"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
volumes:
  todolist-db:
