services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      APP_HOST: localhost:8443
    depends_on:
      - db
      - proxy
  db:
    image: docker.io/postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - todolist-db:/var/lib/postgresql/data
  proxy:
    image: docker.io/caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - 8443
    ports:
      - 8443:8443
volumes:
  todolist-db:
